// IMAANS 3-D store — boot, render loop, shared context. See CONTRACT.md.
import * as THREE from 'three';
import { TIERS, detectTier, isMobileDevice } from './core/tier.js';
import * as layout from './core/layout.js';
import * as kit from './core/kit.js';
import { createAssets } from './core/assets.js';
import { createMaterials } from './core/materials.js';
import { createColliders, createInteract, createHotspots, createFx, createUi } from './core/registry.js';
import { BRAND, catalog } from './core/catalog.js';

// Build order matters: architecture first (room + lights), ui LAST (it needs every registry filled).
const MODULES = [
  ['architecture', () => import('./modules/architecture.js')],
  ['footwear', () => import('./modules/footwear.js')],
  ['apparelRails', () => import('./modules/apparelRails.js')],
  ['apparelDisplay', () => import('./modules/apparelDisplay.js')],
  ['fixtures', () => import('./modules/fixtures.js')],
  ['magic', () => import('./modules/magic.js')],
  ['ui', () => import('./modules/ui.js')],
];
// Relative build cost per module (loader progress only; unknown modules count 1).
const WEIGHT = { architecture: 3, footwear: 2, apparelRails: 3, apparelDisplay: 2, fixtures: 2, magic: 0.5, ui: 0.2 };
// Models each module loads: {module: [model ids]}, generated by tools/perf-models.mjs — baked into the bundle
// by tools/build.mjs, injected as window.__PREFETCH__ by the harnesses. All of them start downloading at boot.
const PREFETCH = (typeof __PREFETCH__ !== 'undefined' && __PREFETCH__) || window.__PREFETCH__ || null; // esbuild define
const PRODUCTION = typeof __MODEL_JSON__ !== 'undefined' && !!__MODEL_JSON__;                          // esbuild define

const params = new URLSearchParams(location.search);
const shotMode = params.has('shot');
const wanted = params.get('modules');
const enabled = new Set(wanted ? wanted.split(',').filter(Boolean) : MODULES.map(m => m[0]));
// Dev-only test modules (e.g. ?modules=_matlab) are imported on demand and never bundled.
for (const name of enabled) if (name.startsWith('_') && !MODULES.some(m => m[0] === name)) MODULES.push([name, () => import(/* @vite-ignore */ './modules/' + name + '.js')]);
if (params.has('noui')) enabled.delete('ui');

const tier = detectTier(params);
const q = { ...TIERS[tier] };

// ---------- renderer ----------
const container = document.getElementById('app') || document.body;
const renderer = new THREE.WebGLRenderer({
  antialias: q.antialias, powerPreference: 'high-performance', stencil: false,
  preserveDrawingBuffer: shotMode,
});
const baseDpr = Math.min(window.devicePixelRatio || 1, q.maxDpr);
let dprScale = 1;
renderer.setPixelRatio(baseDpr);
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.0;
renderer.shadowMap.enabled = q.shadows;
renderer.shadowMap.type = q.shadowType === 'pcfsoft' ? THREE.PCFSoftShadowMap : THREE.PCFShadowMap;
renderer.info.autoReset = false;
// Production: skip the per-program error queries (4 synchronous GL round trips per program on first use).
// Dev keeps them so shader errors are logged.
if (PRODUCTION && !params.has('debug')) renderer.debug.checkShaderErrors = false;
renderer.domElement.id = 'scene';
renderer.domElement.style.touchAction = 'none';
container.appendChild(renderer.domElement);

const scene = new THREE.Scene();
scene.background = new THREE.Color('#0b0a0d');

/** Vertical FOV that keeps a sensible horizontal view in portrait and landscape. */
function fitFov(aspect) {
  if (aspect >= 1) return 60;
  return THREE.MathUtils.clamp(60 + (1 - aspect) * 34, 60, 80); // 390x844 → ~78°
}
const camera = new THREE.PerspectiveCamera(fitFov(innerWidth / innerHeight), innerWidth / innerHeight, 0.05, 80);
camera.position.fromArray(layout.START.pos);
camera.lookAt(new THREE.Vector3().fromArray(layout.START.look));
scene.add(camera);

// ---------- shared context ----------
const events = new EventTarget();
const updaters = [];
const resizers = [];
const readyHooks = [];
const groups = {};

const ctx = {
  THREE, renderer, scene, camera, tier, q, params, shotMode,
  isMobile: isMobileDevice(),
  layout, kit, events,
  time: 0,
  /** Parent group for everything a module adds. ALWAYS add your objects here, not to scene. */
  group(name) {
    if (!groups[name]) { const g = new THREE.Group(); g.name = name; scene.add(g); groups[name] = g; }
    return groups[name];
  },
  onUpdate(fn) { updaters.push(fn); return () => { const i = updaters.indexOf(fn); if (i >= 0) updaters.splice(i, 1); }; },
  onResize(fn) { resizers.push(fn); },
  /** Runs after every module is built (e.g. environment capture, shadow bake). */
  onReady(fn) { readyHooks.push(fn); },
  /** Replaceable by the post-processing owner (magic). */
  render() { renderer.render(scene, camera); },
  /** Shadows are baked once after build; call this after moving a shadow caster. */
  requestShadowUpdate() { renderer.shadowMap.needsUpdate = true; },
  /**
   * Compile the shader programs of something added AFTER the store is ready (a lazily loaded model, a
   * try-on piece…) before showing it, so its first appearance doesn't freeze a phone. Uses the same render
   * target as the main scene pass (post-processing variants). Add the object to its group (visible = false
   * is fine), `await ctx.warm(object)`, then show it. Resolves to the number of new programs.
   */
  warm(object) { return warmObject(object || scene); },
  fitFov,
  controlsEnabled: !shotMode,
};
ctx.assets = createAssets(ctx);
ctx.mats = createMaterials(ctx);
ctx.colliders = createColliders();
ctx.interact = createInteract();
ctx.hotspots = createHotspots();
ctx.fx = createFx();
ctx.brand = BRAND;       // IMAANS brand: name, colours, contact, hours, pages, departments, images
ctx.catalog = catalog;   // the real Imaan's Shoes products: pick(kind,key), card(product), formatPrice…
// Font stacks for DOM + canvas text. The ui module's setup() loads the brand webfonts and awaits them
// (bounded) before any build() runs, so canvas signage drawn in build() can use them.
ctx.fonts = { display: 'Georgia, "Times New Roman", serif', sans: 'system-ui, -apple-system, "Segoe UI", sans-serif' };
ctx.ui = createUi();

// perf: timings are ms since navigation start (performance.now()); see tools/perf-run.mjs
const perf = { prefetch: 0, safetyFired: false, readyHooksMs: 0, warmMs: 0, compileMs: 0, programsAtReady: 0, parallelCompile: false, firstFrameMs: 0, frameSkip: 0, dprChanges: 0 };
const stats = { tier, modules: {}, errors: [], buildMs: 0, perf };
window.__ctx = ctx;
window.__STATS = () => ({
  ...stats,
  calls: renderer.info.render.calls, triangles: renderer.info.render.triangles,
  points: renderer.info.render.points, lines: renderer.info.render.lines,
  geometries: renderer.info.memory.geometries, textures: renderer.info.memory.textures,
  programs: renderer.info.programs ? renderer.info.programs.length : 0,
  // shader programs compiled after 'ready' (target 0: each one is a visible freeze on a phone)
  programsAfterReady: perf.programsAtReady ? renderer.info.programs.length - perf.programsAtReady : 0,
  dpr: renderer.getPixelRatio(), fps: +(1000 / frameMsEma).toFixed(1),
  lights: countLights(),
  models: { requested: ctx.assets.requested(), decodeMs: Math.round(ctx.assets.timing().decodeMs) },
});
function countLights() { let n = 0, s = 0; scene.traverse(o => { if (o.isLight && o.visible && !o.isAmbientLight) { n++; if (o.castShadow) s++; } }); return { lights: n, shadowCasters: s }; }

/** Per-module draw calls / triangles: renders each module group solo once (into the main pass's target → no extra programs). */
window.__MODSTATS = () => {
  const out = {};
  const vis = Object.fromEntries(Object.entries(groups).map(([k, g]) => [k, g.visible]));
  const prevRT = renderer.getRenderTarget();
  renderer.setRenderTarget(mainTargets[0] || null);
  for (const name of Object.keys(groups)) {
    for (const [k, g] of Object.entries(groups)) g.visible = k === name;
    renderer.info.reset(); renderer.render(scene, camera);
    out[name] = { calls: renderer.info.render.calls, triangles: renderer.info.render.triangles, points: renderer.info.render.points };
  }
  renderer.setRenderTarget(prevRT);
  for (const [k, g] of Object.entries(groups)) g.visible = vis[k];
  return out;
};
/** Camera for screenshots: __setCam(px,py,pz, tx,ty,tz, fov?) */
window.__setCam = (px, py, pz, tx, ty, tz, fov) => {
  ctx.controlsEnabled = false;
  camera.position.set(px, py, pz); camera.lookAt(tx, ty, tz);
  if (fov) { camera.fov = fov; camera.updateProjectionMatrix(); }
  events.dispatchEvent(new CustomEvent('camset'));
};

// ---------- resize ----------
function onResize() {
  const w = window.innerWidth, h = window.innerHeight;
  camera.aspect = w / h; camera.fov = fitFov(camera.aspect); camera.updateProjectionMatrix();
  renderer.setSize(w, h);
  for (const fn of resizers) fn(w, h);
}
window.addEventListener('resize', onResize);
window.addEventListener('orientationchange', () => setTimeout(onResize, 250));

// ---------- loop ----------
const clock = new THREE.Clock();
let frameMsEma = 16.7, running = true;
let booting = true;      // the loader covers the canvas until 'ready': run updaters, draw nothing
let readyAt = 0;         // wall-clock s at 'ready'
// Governor + frame-skip run on wall-clock seconds: ctx.time advances ≤ 0.05 s per frame, so below 20 fps it
// runs slow — exactly when the governor has to react.
const wall = () => performance.now() / 1000;
const minScale = Math.min(1, q.minDpr / baseDpr); // never below q.minDpr
const gov = { next: 0, slow: 0, good: 0, ceiling: 1, lastUp: -1e9, cappedAt: 0 };
const skip = { on: false, since: 0, odd: false, still: 0 };
const _camPrev = new Float64Array(9);
function frame() {
  const raw = clock.getDelta();
  const dt = Math.min(raw, 0.05);
  ctx.time += dt;
  renderer.info.reset();
  // one misbehaving module must never freeze the store (three stops the loop when a callback throws)
  for (let i = 0; i < updaters.length; i++) { try { updaters[i](dt, ctx.time); } catch (e) { reportOnce(e, updaters[i]); } }
  if (booting) return;
  // Light frame-skip: a device that can't reach ~22 fps even at the minimum resolution draws every other
  // frame while the camera is at rest (particles keep animating at half rate; the first move → every frame).
  const still = cameraStill(Math.min(raw, 0.25));
  if (skip.on) {
    if (!still || wall() - skip.since > 4) skip.on = false;
    else if ((skip.odd = !skip.odd)) { perf.frameSkip++; return; }
  } else {
    frameMsEma = frameMsEma * 0.93 + Math.min(raw, 0.1) * 1000 * 0.07; // clamp: one long hitch ≠ a slow device
    if (!shotMode && still && frameMsEma > 45 && dprScale <= minScale + 1e-3 && wall() - readyAt > 4) { skip.on = true; skip.since = wall(); }
  }
  try { ctx.render(); } catch (e) { reportOnce(e, ctx.render); }
  if (!perf.firstFrameMs) perf.firstFrameMs = Math.round(performance.now());
  if (!shotMode) governor();
}
/** True while the camera hasn't moved for 0.6 s (position, rotation, fov/aspect; no allocation). */
function cameraStill(dt) {
  const p = camera.position, r = camera.quaternion, c = _camPrev;
  const moved = p.x !== c[0] || p.y !== c[1] || p.z !== c[2] || r.x !== c[3] || r.y !== c[4] || r.z !== c[5] || r.w !== c[6] || camera.fov !== c[7] || camera.aspect !== c[8];
  if (moved) { c[0] = p.x; c[1] = p.y; c[2] = p.z; c[3] = r.x; c[4] = r.y; c[5] = r.z; c[6] = r.w; c[7] = camera.fov; c[8] = camera.aspect; }
  skip.still = moved ? 0 : skip.still + dt;
  return skip.still > 0.6;
}
/**
 * Dynamic resolution: keep phones smooth without a manual quality menu. Down a step (×0.85, never below
 * q.minDpr) after two slow checks (> 25 ms ≈ < 40 fps) or one very slow one (> 34 ms); back up (×1.08) after
 * three good checks (< 18.5 ms — reachable on a 60 Hz display; the old 15 ms threshold never was, so one
 * hitch lowered the resolution for good). A step up that turns slow within 6 s caps the scale there for 30 s
 * (no ping-pong: every change reallocates the post-processing targets).
 */
function governor() {
  const t = wall();
  if (t < gov.next) return;
  gov.next = t + 1;
  if (gov.ceiling < 1 && t - gov.cappedAt > 30) gov.ceiling = 1;
  const ms = frameMsEma;
  if (ms > 25 && dprScale > minScale + 1e-3) {
    gov.good = 0;
    if (++gov.slow >= 2 || ms > 34) {
      if (t - gov.lastUp < 6) { gov.ceiling = Math.max(minScale, dprScale / 1.08); gov.cappedAt = t; }
      setDprScale(Math.max(minScale, dprScale * 0.85)); gov.slow = 0;
    }
  } else if (ms < 18.5 && dprScale < gov.ceiling - 1e-3) {
    gov.slow = 0;
    if (++gov.good >= 3) { gov.good = 0; gov.lastUp = t; setDprScale(Math.min(gov.ceiling, dprScale * 1.08)); }
  } else { gov.slow = 0; gov.good = 0; }
}
const _reported = new WeakSet();
function reportOnce(e, fn) { if (_reported.has(fn)) return; _reported.add(fn); console.error('[loop]', e); stats.errors.push('loop: ' + (e && e.message)); }
function setDprScale(s) {
  dprScale = s; renderer.setPixelRatio(baseDpr * s);
  renderer.setSize(window.innerWidth, window.innerHeight);
  for (const fn of resizers) fn(window.innerWidth, window.innerHeight);
  perf.dprChanges++;
  gov.next = wall() + 1.5; // let the realloc frame pass before judging the new size
}
let paused = false;      // IMAANS_STORE.pause(): the embedding page stopped the store (e.g. left its route)
let loopStarted = false; // boot has started the loop (before that, resume() must not start it early)
/** Start / stop the render loop from the current state (tab visible, not paused, boot past setup). */
function syncLoop() {
  const on = loopStarted && running && !paused;
  renderer.setAnimationLoop(on ? frame : null);
  clock.getDelta(); // the time spent stopped is never one giant frame
  if (on) { frameMsEma = 16.7; gov.next = wall() + 2; gov.slow = gov.good = 0; skip.on = false; skip.still = 0; }
}
document.addEventListener('visibilitychange', () => {
  running = !document.hidden;
  syncLoop(); // hidden tab: no frames at all
});

// ---------- embedding API (website integration — see INTEGRATION.md §4) ----------
// window.IMAANS_STORE.pause() stops the render loop and with it the governor, frame-skip, updaters and
// particles (nothing runs while paused; the WebGL context and everything built stay alive). resume() restarts
// cleanly: fresh clock (no time jump), governor state reset, a resize catch-up if the window changed meanwhile.
// ctx.events gets 'pause' / 'resume' events. Calling either twice is harmless.
let _pausedSize = '';
window.IMAANS_STORE = {
  ctx,
  pause() {
    if (paused) return;
    paused = true; _pausedSize = window.innerWidth + 'x' + window.innerHeight;
    syncLoop();
    events.dispatchEvent(new CustomEvent('pause'));
  },
  resume() {
    if (!paused) return;
    paused = false;
    if (window.innerWidth + 'x' + window.innerHeight !== _pausedSize) onResize();
    syncLoop();
    events.dispatchEvent(new CustomEvent('resume'));
  },
  isPaused() { return paused; },
};

// ---------- shader warm-up ----------
// Phones compile every program on first sight. Before the loader lifts, compile everything the store can
// show — from every direction — into the render target the main pass really uses, and bake the shadows.
let mainTargets = [];    // render target(s) the main scene pass draws into (null = the screen)
/** Run ctx.render() once with the scene pass skipped, to learn its target(s); post passes compile meanwhile. */
function findMainTargets() {
  const seen = new Set(); const orig = renderer.render;
  renderer.render = function (s, c) { if (s === scene) { seen.add(renderer.getRenderTarget()); return; } return orig.call(this, s, c); };
  try { ctx.render(); } catch (e) { /* the real render reports it */ } finally { renderer.render = orig; }
  return seen.size ? [...seen] : [null];
}
/** compileAsync(object) into each main target, then take every program's first-use queries now. */
async function compileFor(object) {
  const n0 = renderer.info.programs.length, prev = renderer.getRenderTarget();
  for (const rt of mainTargets.length ? mainTargets : [null]) {
    renderer.setRenderTarget(rt);
    // with KHR_parallel_shader_compile the driver links in parallel and we poll; without it compileAsync is just
    // compile() + a timer (and a console warning), so call compile() directly
    try { if (hasParallel() && renderer.compileAsync) await renderer.compileAsync(object, camera, scene); else renderer.compile(object, camera, scene); }
    catch (e) { console.warn('[warm] compile', e && e.message); }
    finally { renderer.setRenderTarget(prev); }
  }
  // Uniform/attribute lookup + link-status query happen on a program's first use: do them behind the loader.
  const progs = renderer.info.programs;
  for (let i = n0; i < progs.length; i++) { try { progs[i].getUniforms(); progs[i].getAttributes(); } catch (e) { /* lost context */ } }
  return renderer.info.programs.length - n0;
}
let _parallel = null;
function hasParallel() { if (_parallel === null) _parallel = renderer.extensions.has('KHR_parallel_shader_compile'); return _parallel; }
async function warmObject(object) {
  if (!mainTargets.length) mainTargets = findMainTargets();
  return compileFor(object);
}
async function warmUp() {
  const t0 = performance.now();
  perf.parallelCompile = hasParallel();
  mainTargets = findMainTargets();
  await compileFor(scene);
  perf.compileMs = Math.round(performance.now() - t0);
  // One real frame with frustum culling off: everything draws once (textures upload, the shadow maps bake with
  // their depth-material variants, post-processing and background programs compile) — all behind the loader.
  const culled = [];
  scene.traverse(o => { if (o.frustumCulled) { o.frustumCulled = false; culled.push(o); } });
  renderer.shadowMap.autoUpdate = false; renderer.shadowMap.needsUpdate = true;
  try { ctx.render(); } catch (e) { console.warn('[warm] render', e && e.message); }
  finally { for (const o of culled) o.frustumCulled = true; }
  renderer.info.reset();
  perf.warmMs = Math.round(performance.now() - t0);
  perf.programsAtReady = renderer.info.programs.length;
}

// ---------- boot ----------
async function boot() {
  const t0 = performance.now();
  const list = MODULES.filter(([name]) => enabled.has(name));
  // Every model the enabled modules need starts downloading now, in parallel (modules still build in order).
  if (PREFETCH) {
    const ids = [...new Set(list.flatMap(([name]) => PREFETCH[name] || []))];
    perf.prefetch = ids.length;
    ctx.assets.prefetch(ids);
  }
  const loaded = await Promise.all(list.map(([name, load]) => load().then(m => [name, m], (e) => {
    console.error('[boot] failed to import', name, e); stats.errors.push(name + ': import ' + e.message); return null;
  })));
  const mods = loaded.filter(Boolean);
  // setup(): early, cheap hooks (e.g. the ui module shows its loader)
  for (const [name, m] of mods) if (m.setup) { try { await m.setup(ctx); } catch (e) { console.error(name, e); stats.errors.push(name + ': setup ' + e.message); } }
  loopStarted = true; syncLoop();   // = setAnimationLoop(frame) unless the tab is hidden or the page paused us
  const wTotal = mods.reduce((a, [name]) => a + (WEIGHT[name] ?? 1), 0) || 1;
  let wDone = 0;
  for (const [name, m] of mods) {
    const ts = performance.now();
    ctx.ui.setLoading(0.86 * wDone / wTotal, name);
    try { if (m.build) await m.build(ctx); }
    catch (e) { console.error('[boot] module failed', name, e); stats.errors.push(name + ': ' + (e && e.message)); }
    stats.modules[name] = { ms: Math.round(performance.now() - ts) };
    wDone += WEIGHT[name] ?? 1;
  }
  // 'ready' phase (textures decode, environment capture, shader warm-up): the loader shows "Opening the doors"
  // at ~90 %; it reaches 100 % when the store is really drawable. Never trap the visitor behind it.
  ctx.ui.setLoading(0.9, 'ready');
  // A ready hook / warm-up that never settles must not leave the visitor on an undrawn canvas either: after
  // 15 s the loader lifts AND drawing starts (a later first-view shader compile beats a store that never opens).
  const safety = setTimeout(() => { ctx.ui.setLoading(1, 'ready'); if (booting) { booting = false; readyAt = wall(); perf.safetyFired = true; } }, 15000);
  const tr = performance.now();
  for (const fn of readyHooks) { try { await fn(ctx); } catch (e) { console.error('[ready]', e); stats.errors.push('ready: ' + e.message); } }
  for (const [name, m] of mods) if (m.ready) { try { await m.ready(ctx); } catch (e) { console.error(name, e); stats.errors.push(name + ': ready ' + e.message); } }
  perf.readyHooksMs = Math.round(performance.now() - tr);
  ctx.ui.setLoading(0.95, 'ready');
  try { await warmUp(); } catch (e) { console.warn('[warm]', e); }
  clearTimeout(safety);
  ctx.ui.setLoading(1, 'ready');
  stats.buildMs = Math.round(performance.now() - t0);
  booting = false; readyAt = wall(); frameMsEma = 16.7; gov.next = readyAt + 3; // governor waits out the loader fade
  events.dispatchEvent(new CustomEvent('ready'));
  if (window.__PREFETCH__ && !PRODUCTION) { // dev/harness: flag models the prefetch scan missed (tools/perf-models.mjs)
    const want = new Set(list.flatMap(([name]) => PREFETCH[name] || []));
    const missed = ctx.assets.requested().filter(id => !want.has(id));
    if (missed.length) console.warn('[assets] loaded without prefetch (add a recognised call shape to tools/perf-models.mjs):', missed.join(', '));
  }
  let n = 0;
  const waitFrames = () => { if (++n > 3) { window.__STORE_READY = true; } else requestAnimationFrame(waitFrames); };
  requestAnimationFrame(waitFrames);
}
// never leave the canvas undrawn: whatever happens in boot, drawing starts when it ends
boot().catch((e) => { console.error('[boot]', e); stats.errors.push('boot: ' + (e && e.message)); }).finally(() => { booting = false; });

// Frame-time overlay: ?debug=1
if (params.has('debug')) {
  const el = document.createElement('pre');
  el.style.cssText = 'position:fixed;left:8px;bottom:8px;z-index:99;color:#9f9;font:11px monospace;background:#000a;padding:6px;margin:0;pointer-events:none';
  document.body.appendChild(el);
  setInterval(() => { const s = window.__STATS(); el.textContent = `${s.tier} ${s.fps}fps dpr ${s.dpr.toFixed(2)}\ncalls ${s.calls} tris ${(s.triangles / 1000).toFixed(0)}k pts ${s.points}\nprog ${s.programs} (+${s.programsAfterReady} late) tex ${s.textures}`; }, 500);
}
