// IMAANS brand + product catalogue for the 3D store.
// Data comes from the real Imaan's Shoes website (src/core/imaans.data.js, generated by
// tools/imaans-import.mjs). EVERY tappable product in the store must map to one of these products
// so the store can later be dropped into the website and share its basket (IS.cart.add({productId,
// sizeId, colourId, qty})).
//
//   import { BRAND, catalog } from '../core/catalog.js'   (also on ctx.catalog / ctx.brand)
//   catalog.pick('dress', 'bay3-7')      → a stable product for a 3-D item of that kind
//   catalog.card(product, {colorways})   → an interact info object for ctx.interact.add(...)
//   catalog.formatPrice(129900)          → 'R 1 299.00'   (identical to the website's formatter)
import { IMAANS as SNAPSHOT } from './imaans.data.js';
import { adaptSiteContent } from './imaans.adapter.js';

// Inside the Imaan's website the live content document wins (window.IS.content once loaded, else the
// static fallback), so the store always shows today's products & prices. Standalone → the snapshot.
// Live product photos are the site's own URLs; relative ones ('img/p-….jpg') are resolved against the page
// so catalog.imageUrl() never prefixes them with the store's asset base.
function liveContent() {
  try {
    const w = typeof window !== 'undefined' ? window : null;
    const c = w && ((w.IS && w.IS.content && typeof w.IS.content === 'object' && w.IS.content) || w.IS_FALLBACK_CONTENT);
    if (!c || !Array.isArray(c.products) || !c.products.length) return null;
    const abs = (u) => { try { return /^(\/|https?:|data:|blob:)/.test(u) ? u : new URL(u, document.baseURI).href; } catch (e) { return u; } };
    const data = adaptSiteContent(c, p => { const u = p.images && p.images[0] && p.images[0].url; return u ? abs(u) : null; });
    if (!data.products.length) { console.warn('[catalog] live content has no visible products — using the built-in snapshot'); return null; }
    return data;
  } catch (e) { console.warn('[catalog] live content unreadable — using the built-in snapshot:', e && e.message); return null; }
}
const IMAANS = liveContent() || SNAPSHOT;
export const CONTENT_SOURCE = IMAANS === SNAPSHOT ? 'snapshot' : 'live';
const CURRENCY = { code: 'ZAR', symbol: 'R', position: 'before', decimals: 2, thousands: ' ', decimalSep: '.', ...((IMAANS.site && IMAANS.site.currency) || {}) };

// The three 3-D departments always exist (their zones are built regardless of the content); names and
// descriptions come from the site's matching categories (imaans.adapter.js maps renamed ones).
const DEPTS = ['clothes', 'shoes', 'accessories'].map(id => {
  const k = (IMAANS.categories || []).find(k => k && k.id === id) || {};
  return { id, slug: k.slug || id, name: k.name || id[0].toUpperCase() + id.slice(1), description: k.description || '' };
});
/** Promos inside their startsAt/endsAt window (the site's rule), evaluated when the store loads. */
const now = Date.now();
const livePromos = (IMAANS.promos || []).filter(p => {
  const from = p.startsAt ? Date.parse(p.startsAt) : NaN, until = p.endsAt ? Date.parse(p.endsAt) : NaN;
  return !(from > now) && !(until < now);
});

export const BRAND = {
  name: 'IMAANS',                       // the wordmark (logo lettering is wide classical serif caps + crown)
  legalName: (IMAANS.site && IMAANS.site.name) || 'Imaan’s Shoes', // the business name used in copy (site.name)
  line: 'Shoes & Clothing',             // line under the wordmark
  slogan: 'Step into style. Live confidently.',
  tagline: (IMAANS.site && IMAANS.site.tagline) || '', // 'Clothes, shoes & everything in between'
  // one line about the shop: the first sentence of the site's footer blurb (content), else the default
  story: (() => { const b = String((IMAANS.footer && IMAANS.footer.blurb) || '').trim(), m = b.match(/^.{20,160}?[.!?](\s|$)/); return (m ? m[0] : b.length <= 160 ? b : '').trim() || 'A small family-run boutique on Sir Lowry Road in Woodstock, Cape Town, since 2019.'; })(),
  colours: {
    black: '#1b1b1b', ink: '#050506', gold: '#b08d57',
    goldLight: '#f6dd8c', goldMid: '#d9ab48', goldDeep: '#a97a1f', // the logo's gold gradient
    ivory: '#faf7f2', white: '#ffffff', border: '#e8e3da', muted: '#6b6b6b', sale: '#b4342a',
  },
  announcement: IMAANS.announcement || '', // 'Free delivery on orders over R800 · Collection from Woodstock is always free'
  contact: { addressLines: [], ...(IMAANS.contact || {}) }, // phoneDisplay, whatsapp, email, addressLines[], mapUrl
  hours: { note: '', ...(IMAANS.hours || {}), days: (IMAANS.hours && Array.isArray(IMAANS.hours.days)) ? IMAANS.hours.days : [] }, // {note, days:[{label, open, close, closed}]}
  social: IMAANS.social || [],
  checkout: IMAANS.checkout || { mode: 'whatsapp' }, // mode 'whatsapp', messageIntro/Outro
  pages: IMAANS.pages || [],            // about, shipping-delivery, returns, size-guide, faq  ({slug,title,blocks:[{heading,body,items:[{q,a}]}]})
  promos: livePromos,                   // e.g. 'The Spring Edit has landed' (headline promos first, date window applied)
  testimonials: IMAANS.testimonials || [],
  departments: DEPTS,                   // always [{id:'clothes'}, {id:'shoes'}, {id:'accessories'}] with the site's names
  images: {                             // under assets/
    logo: 'brand/logo.svg', banner: 'brand/banner.webp',
    campaignClothing: 'brand/campaign-clothing.webp', campaignShoes: 'brand/campaign-shoes.webp', springEdit: 'brand/spring-edit.webp',
  },
};

/** The crown from the IMAANS logo, drawn on a 2D canvas centred at (cx, cy), `w` wide. */
export function drawCrown(g, cx, cy, w, fill = BRAND.colours.gold) {
  const s = w / 192;
  g.save(); g.translate(cx, cy); g.scale(s, s); g.fillStyle = fill;
  g.beginPath();
  g.moveTo(-96, 35); g.lineTo(-96, -6); g.lineTo(-58, 26); g.lineTo(-26, -45); g.lineTo(0, -67); g.lineTo(26, -45);
  g.lineTo(58, 26); g.lineTo(96, -6); g.lineTo(96, 35); g.quadraticCurveTo(96, 51, 80, 51); g.lineTo(-80, 51);
  g.quadraticCurveTo(-96, 51, -96, 35); g.closePath(); g.fill();
  g.beginPath(); if (g.roundRect) g.roundRect(-96, 35, 192, 24, 6); else g.rect(-96, 35, 192, 24); g.fill();
  g.restore();
}

/** The logo's gold as a vertical canvas gradient between y0 and y1. */
export function goldGradient(g, y0, y1) {
  const gr = g.createLinearGradient(0, y0, 0, y1);
  gr.addColorStop(0, BRAND.colours.goldLight); gr.addColorStop(0.55, BRAND.colours.goldMid); gr.addColorStop(1, BRAND.colours.goldDeep);
  return gr;
}

// 3-D item kind → words matched against a product's tags and name (first match list wins, then fallbacks).
const KINDS = {
  // clothes
  dress: ['dresses', 'dress'], slipdress: ['satin', 'slip'], maxi: ['maxi'], sundress: ['sundress', 'broderie'],
  shirt: ['shirts', 'shirt'], blouse: ['blouses', 'blouse'], top: ['tops', 'camisole', 'breton'], tee: ['t-shirt', 'tops'],
  knit: ['knitwear', 'jumpers', 'jumper'], sweater: ['jumpers', 'knitwear'], cardigan: ['cardigans', 'cardigan'], cable: ['cable'],
  hoodie: ['hooded', 'quilted', 'knitwear'], skirt: ['skirts', 'skirt'], trousers: ['trousers', 'trouser', 'chino'],
  jeans: ['jeans', 'jean'], denim: ['denim'], blazer: ['blazers', 'blazer', 'waistcoats'], waistcoat: ['waistcoats'],
  coat: ['coats', 'overcoat'], jacket: ['jackets', 'jacket'], trench: ['coats', 'overcoat'], puffer: ['quilted'],
  shorts: ['shorts'], jumpsuit: ['jumpsuit', 'co-ord'], coord: ['co-ord'], linen: ['linen'],
  // shoes
  sneaker: ['sneakers', 'trainers', 'sneaker', 'runner'], boot: ['boots', 'boot'], chelsea: ['chelsea'],
  heel: ['heels', 'court', 'heel'], pump: ['court', 'heels'], stiletto: ['pointed', 'court', 'heels'],
  flat: ['flats', 'flat', 'ballet'], loafer: ['loafer', 'brogue', 'monk'], brogue: ['brogues', 'brogue'],
  sandal: ['sandals', 'sandal'], slide: ['slides', 'slide', 'slider'], mule: ['mules', 'mule'], wedge: ['wedges', 'wedge', 'espadrille'],
  // accessories
  bag: ['bags', 'bag'], tote: ['totes', 'tote'], clutch: ['clutch'], crossbody: ['crossbody'], backpack: ['backpacks'],
  handbag: ['crossbody', 'totes', 'clutch', 'bags'],
  sunglasses: ['sunglasses'], scarf: ['scarves', 'scarf'], hat: ['hats', 'hat', 'beanie'],
  jewellery: ['jewellery'], earrings: ['earrings'], necklace: ['necklaces', 'necklace'], bracelet: ['bracelets'],
  wallet: ['wallets', 'purse', 'card holder'], belt: ['belts', 'belt'], gloves: ['gloves'], umbrella: ['umbrellas'],
  socks: ['socks'], keyring: ['keyrings', 'charms'], watch: ['jewellery', 'gifts'], perfume: ['gifts'],
};
const KIND_CATEGORY = {};
for (const k of Object.keys(KINDS)) KIND_CATEGORY[k] = 'clothes';
['sneaker', 'boot', 'chelsea', 'heel', 'pump', 'stiletto', 'flat', 'loafer', 'brogue', 'sandal', 'slide', 'mule', 'wedge'].forEach(k => (KIND_CATEGORY[k] = 'shoes'));
['bag', 'tote', 'clutch', 'crossbody', 'backpack', 'handbag', 'sunglasses', 'scarf', 'hat', 'jewellery', 'earrings', 'necklace', 'bracelet', 'wallet', 'belt', 'gloves', 'umbrella', 'socks', 'keyring', 'watch', 'perfume']
  .forEach(k => (KIND_CATEGORY[k] = 'accessories'));

function hash(s) { s = String(s); let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }

const PRODUCTS = IMAANS.products || [];
const byId = new Map(PRODUCTS.map(p => [p.id, p]));
const bySlug = new Map(PRODUCTS.map(p => [p.slug, p]));
const matchCache = new Map();

function matches(kind) {
  if (matchCache.has(kind)) return matchCache.get(kind);
  const words = KINDS[kind] || [kind];
  const cat = KIND_CATEGORY[kind];
  const pool = PRODUCTS.filter(p => !cat || p.category === cat);
  // whole-word matches against tags and name words (so 'coats' never matches 'waistcoats'); the union of
  // every word, ranked by the earliest word that matched
  const hit = (p, w) => (p.tags || []).some(t => t === w || t === w + 's' || String(t).split(' ').includes(w)) ||
    String(p.name || '').toLowerCase().split(/[\s-]+/).some(n => n === w || n === w + 's' || (w.includes(' ') && String(p.name || '').toLowerCase().includes(w)));
  const rank = p => { const i = words.findIndex(w => hit(p, w)); return i < 0 ? 99 : i; };
  let out = pool.filter(p => rank(p) < 99).sort((a, b) => rank(a) - rank(b));
  if (!out.length) out = pool.length ? pool : PRODUCTS;
  matchCache.set(kind, out);
  return out;
}

/** Money exactly like the website's formatMoney() (js/core.js): site.currency symbol/position/decimals/separators. */
function formatPrice(cents) {
  const c = CURRENCY;
  const n = typeof cents === 'number' && isFinite(cents) ? cents : (typeof cents === 'string' && cents.trim() !== '' && isFinite(+cents) ? +cents : 0);
  const abs = Math.abs(Math.round(n)), dec = typeof c.decimals === 'number' ? c.decimals : 2;
  let whole, frac = '';
  if (dec === 0) whole = Math.round(abs / 100);
  else if (dec === 1) { const t = Math.round(abs / 10); whole = Math.floor(t / 10); frac = String(t % 10); }
  else { whole = Math.floor(abs / 100); frac = String(100 + (abs % 100)).slice(1); }
  let body = String(whole).replace(/\B(?=(\d{3})+(?!\d))/g, ',').split(',').join(typeof c.thousands === 'string' ? c.thousands : ' ');
  if (dec > 0) body += (c.decimalSep || '.') + frac;
  const sym = typeof c.symbol === 'string' ? c.symbol : '';
  const out = c.position === 'after' ? body + (sym ? ' ' + sym : '') : (sym ? sym + ' ' : '') + body;
  return n < 0 && abs ? '-' + out : out;
}

const BADGE = { new: 'New in', sale: 'Sale', bestseller: 'Bestseller', limited: 'Limited', 'last-few': 'Last few' };
/** Badge label: the known ones, else the badge itself made readable ('eid-special' → 'Eid special'). */
const badgeLabel = (b) => (b ? BADGE[b] || (String(b).replace(/[-_]+/g, ' ').trim().replace(/^./, ch => ch.toUpperCase())).slice(0, 24) : '');

export const catalog = {
  /** 'live' (the website's own content document) or 'snapshot' (src/core/imaans.data.js). */
  source: CONTENT_SOURCE,
  /** Site shop settings the store honours: showOutOfStock=false → sold-out products are left out. */
  settings: { showPrices: true, showOutOfStock: true, ...(IMAANS.settings || {}) },
  currency: CURRENCY,
  products: PRODUCTS,
  categories: IMAANS.categories || [],
  sizeGuides: IMAANS.sizeGuides,
  kinds: Object.keys(KINDS),
  get(idOrSlug) { return byId.get(idOrSlug) || bySlug.get(idOrSlug) || null; },
  byCategory(cat) { return PRODUCTS.filter(p => p.category === cat); },
  /** All products matching a 3-D item kind (see KINDS), best matches first. */
  all(kind) { return matches(kind).slice(); },
  /** A stable product for a 3-D item: same (kind, key) → same product, different keys spread across the pool. */
  pick(kind, key = 0) { const m = matches(kind); return m.length ? m[hash(kind + ':' + key) % m.length] : null; },
  formatPrice,
  priceOf(p) { return p.salePriceCents != null ? p.salePriceCents : p.priceCents; },
  /** Image URL: snapshot paths are relative to the assets base; live-site paths are site URLs (absolute). */
  imageUrl(p, base = '') { return !p || !p.image ? null : (/^(\/|https?:|data:|blob:)/.test(p.image) ? p.image : base + p.image); },
  /** Website deep link (for when the store is embedded in the Imaan's site). */
  siteUrl(p) { return '#/product/' + encodeURIComponent(p.slug); },
  /**
   * Interact/card info for a product. Keeps the fields the ui already reads (title, subtitle, price,
   * tag, sizes, colorways, actions) and adds the catalogue ones (productId, slug, image, sizeOptions,
   * colourOptions, priceCents, wasPrice, url, category).
   * opts: { colorways: [{name, swatch, apply}] (3-D recolour hooks; matched to product colours by index),
   *         actions: [...], onTap(hit), tag, subtitle }
   */
  card(p, opts = {}) {
    if (!p) return null;
    const sale = p.salePriceCents != null;
    const colours = (p.colours || []).map((c, i) => {
      const hook = opts.colorways && opts.colorways.length ? opts.colorways[i % opts.colorways.length] : null;
      return { id: c.id, name: c.label, swatch: c.swatch, apply: hook && hook.apply ? hook.apply : undefined };
    });
    return {
      productId: p.id, slug: p.slug, category: p.category,
      title: p.name,
      subtitle: opts.subtitle || p.short,
      price: formatPrice(sale ? p.salePriceCents : p.priceCents),
      wasPrice: sale ? formatPrice(p.priceCents) : null,
      priceCents: sale ? p.salePriceCents : p.priceCents,
      tag: opts.tag || (sale ? 'Sale' : badgeLabel((p.badges || [])[0]) || (p.featured ? 'Featured' : '')),
      image: p.image, imageAlt: p.imageAlt,
      sizes: (p.sizes || []).map(s => (s.inStock ? s.label : s.label + ' (sold out)')),
      sizeOptions: p.sizes || [],
      colourOptions: p.colours || [],
      colorways: colours,
      inStock: p.inStock,
      url: catalog.siteUrl(p),
      actions: opts.actions || [],
      onTap: opts.onTap,
    };
  },
};
